Hw 2
ddddi21/AndroidCourse pull request #2
Opened 2020-09-20 23:33 UTC by ddddi21

telegram is done

2020-09-28 00:09 UTC, ddddi21 commented
наверное, не стоило брать телеграм, но было уже слишком поздно.....

2020-10-04 22:39 UTC, NailShaykhrazievItis requested changes

2020-10-04 22:39 UTC, NailShaykhrazievItis commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.0.0-beta01'
актуальная версия com.google.android.material:material:1.2.1
можно не исправлять, но в будущем используйте последнюю версию

2020-10-04 22:39 UTC, NailShaykhrazievItis commented on app/src/main/res/drawable-v24/dimens.xml
> +            android:bottomLeftRadius="70sp"
думаю тут должно быть dp, sp используются для размера текста, в остальных случаях дп

2020-10-04 22:39 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintTop_toTopOf="parent"
Не обязательно все поля сетиться относительно родителя, думаю этот элемент мог быть спокойно быть после ti_username
app:layout_constraintTop_toBottoOf="@id/ti_username"

2020-10-04 22:40 UTC, NailShaykhrazievItis commented
Без скриншотов невозможно оценить вашу работу. За первую часть 1 балл из 3 , вторая часть выполнено хорошо.

2020-10-04 23:34 UTC, ddddi21 commented on app/build.gradle
> +    implementation 'com.google.android.material:material:1.0.0-beta01'
у меня именно без этой версии TextInputLayaout ошибку выкидывал

2020-10-04 23:35 UTC, ddddi21 commented
> Без скриншотов невозможно оценить вашу работу. За первую часть 1 балл из 3 , вторая часть выполнено хорошо.

так у меня же есть скриншоты в ветке..

2020-10-04 23:36 UTC, ddddi21 commented on app/src/main/res/layout/activity_registration.xml
> +        app:layout_constraintTop_toTopOf="parent"
просто мне так удобнее было верстать. это нужно исправлять?

2020-10-04 23:40 UTC, ddddi21 commented
> > Без скриншотов невозможно оценить вашу работу. За первую часть 1 балл из 3 , вторая часть выполнено хорошо.
> 
> так у меня же есть скриншоты в ветке..

add files via upload где

2020-10-05 11:21 UTC, ddddi21 commented
![my_profile](https://user-images.githubusercontent.com/55531213/95073749-0933d980-0716-11eb-9680-be8cfd06db35.jpg)
![original_profile](https://user-images.githubusercontent.com/55531213/95073752-0afd9d00-0716-11eb-881c-93d689992594.jpg)
![registration](https://user-images.githubusercontent.com/55531213/95073756-0b963380-0716-11eb-8e93-da34608ea9af.jpg)

2020-12-29 17:19 UTC, NailShaykhrazievItis approved these changes

2020-12-29 19:01 UTC, closed without merging