add hw6
ddddi21/AndroidCourse pull request #5
Opened 2020-10-22 20:40 UTC by ddddi21

2020-10-22 20:44 UTC, ddddi21 commented
![QFupKjcct5w](https://user-images.githubusercontent.com/55531213/96927924-7ab6aa80-14c0-11eb-9bc5-cb76d5a35ff3.jpg)
![NLuijJ9AqBg](https://user-images.githubusercontent.com/55531213/96927930-7d190480-14c0-11eb-90d5-bd1a766ef28e.jpg)
![OftPlLMpj74](https://user-images.githubusercontent.com/55531213/96927939-7f7b5e80-14c0-11eb-8140-ccf5771f1e51.jpg)
![3u5UoMd0DsI](https://user-images.githubusercontent.com/55531213/96927946-830ee580-14c0-11eb-8bf9-129c867cdc18.jpg)

2020-12-29 15:07 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/androidcourse/AboutCatActivity.kt
> +        var thisCats = CatRepository.getCatById(intent.getIntExtra("id", 0))
CatRepository.getCatById(intent.getIntExtra("id", 0))?.also {
  init(it)
 }

2020-12-29 15:16 UTC, NailShaykhrazievItis requested changes

2020-12-29 15:16 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/androidcourse/CatHolder.kt
> +            it.context.startActivity(Intent(it.context,AboutCatActivity::class.java).putExtra("id", cat?.id))
холдер не должен заниматься навигацией, не его зона ответсвенности. Он умеет работать с конкретной элементом(создавать его и биндить туда данные, и иметь слушатели). Холдер передает коллбек в активити или фрагмент и он уже занимается навигацией, а в коллбеке передаешь id

тем более ты уже передаешь коллбек, у тебя тут должно быть: 

itemView.setOnClickListener{
cat?.also(itemClick)
}

2020-12-29 15:16 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/androidcourse/CatHolder.kt
> +    private val itemClick: (Cat) ->Unit
пробел перед юнит

2020-12-29 15:16 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/androidcourse/CatRepository.kt
> +        cats.forEach{
fun getCatById(id:Int): Cat? = сats.find { it.id == id}

2020-12-29 15:16 UTC, NailShaykhrazievItis commented
Последний скрин прям хорошо

2021-11-26 19:33 UTC, closed without merging